futurewei-cloud/alcor-control-agent

- test/e2e_tests/test_aca_mizar.py
The latest Alcor control plane implementation uses endpoint hosts for switch and router placement. The change updates the onebox test script to reflect that.
> update onebox test script based on latest implementation

- include/aca_net_config.h
- include/aca_ovs_programmer.h
- include/aca_vlan_manager.h
- src/CMakeLists.txt
- src/comm/aca_comm_mgr.cpp
- src/dp_abstraction/aca_dataplane_ovs.cpp
- src/ovs/aca_ovs_programmer.cpp
- src/ovs/aca_vlan_manager.cpp
- test/gtest/aca_tests.cpp
This PR added Vlan manager implementation and test cases to enforce the VPC security boundary on the host and further provide tenant isolation between different VPCs. 
The change includes:
- new vlan manager class
- changes in ACA_OVS_Programmer to use the vlan manager class
- new two machine (manual) test case to test tenet isolation in different VPC
> Adding Vlan manager implementation and test cases

- build/aca-machine-init.sh
- include/aca_config.h
- include/aca_ovs_programmer.h
- include/aca_util.h
- src/dp_abstraction/aca_dataplane_ovs.cpp
- src/dp_abstraction/aca_goal_state_handler.cpp
- src/ovs/aca_ovs_programmer.cpp
- test/gtest/aca_tests.cpp
this is the Hotfix to enable openstack nova integration, it addressed two major issues:
1. the port_name receive from nova call is empty, aca will use the port_id to generate the port_name based on the same algorithm nova compute agent uses
2. for the compute host port update call, nova compute agent is waiting for Alcor to return before creating the ovs port to plug in the new tap interface, the short term fix is for aca to return a pending call back to Alcor, and then set the vlan id on the ovs port in the background thread
We also updated the aca deployment script to make our deployment easier.
> Hotfix to enable openstack nova integration

- README.md
- docs/major_components.adoc
- src/comm/aca_async_grpc_server.cpp
- src/comm/aca_comm_mgr.cpp
- src/dp_abstraction/aca_dataplane_ovs.cpp
- src/net_config/aca_net_config.cpp
- src/ovs/aca_ovs_l2_programmer.cpp
- src/ovs/aca_ovs_l3_programmer.cpp
- src/ovs/aca_vlan_manager.cpp
- test/func_tests/gs_tests.cpp
- test/gtest/aca_tests.cpp
This PR includes the following changes:
- Remove error logging for port create pending status return
- Optimized port create processing by removing ovs bridge check at the begining
- Added port create parallel programming time data
- Added new test case 10_l2_neighbor_CREATE for performance measurement
> [Enhancements] remove error logging for pending status return and update documentations

- include/aca_config.h
- src/README.md
- src/aca_main.cpp
- src/comm/aca_grpc.cpp
- src/ovs/aca_ovs_l2_programmer.cpp
- src/ovs/aca_ovs_l3_programmer.cpp
- test/func_tests/gs_tests.cpp
- test/gtest/aca_tests.cpp
Using DVR mac prefix (e.g., fe:16:11:) together with internal vlan ID based on incoming tunnel ID, we can determine the incoming packet is coming from a neighbor host DVR and restore src mac to the port's gateway MAC. This removes the need of neighbor host DVR mac for L3 neighbor configuration. 
This change includes:
1. define a mac prefix to indicate it is a host dvr mac (aca_config.h)
2. update L3 neighbor configuration handling (aca_ovs_l3_programming.cpp)
3. update routing test to confirm passing with new algorithm (aca_test.cpp) 
Thanks to the suggestion from https://github.com/futurewei-cloud/alcor/issues/375
> [Enhancement] Remove the needed for neighbor host DVR mac in L3 neighbor configuration

- include/aca_dhcp_server.h
- src/comm/aca_comm_mgr.cpp
- src/dhcp/aca_dhcp_server.cpp
- src/ovs/aca_ovs_control.cpp
__Bug Description__
Mac addresses have a few valid forms and may come in upper or lower case. Standardizing mac address for DHCP processing is needed to enable E2E integration of Alcor+Openstack because the goal state message received by ACA could be in the format of AA-BB-CC-DD-EE-FF but the received DHCP packet mac address could be aa:bb:cc:dd:ee:ff. 
__Proposed Change__
The change is to standardize the mac address to aa:bb:cc:dd:ee:ff before add/remove/update/find in the DHCP database. Additional log statements are also added to improve diagnosability for the DHCP E2E.
> [Hotfix] standardize mac address for DHCP and improve logging

- build/Dockerfile
- build/build.sh
- src/ovs/aca_ovs_l2_programmer.cpp
> Adding container based ACA unit test with build for cross platform development

- include/aca_grpc.h
- src/aca_main.cpp
- src/comm/aca_grpc.cpp
#139 
We used valgrind to find a memory leak and partially fixed it. Get the following result：
==9168== LEAK SUMMARY:
==9168==    definitely lost: 0 bytes in 0 blocks
==9168==    indirectly lost: 0 bytes in 0 blocks
==9168==      possibly lost: 1,503 bytes in 6 blocks
==9168==    still reachable: 71,253 bytes in 175 blocks
==9168==         suppressed: 0 bytes in 0 blocks
==9168==
==9168== For counts of detected and suppressed errors, rerun with: -v
==9168== ERROR SUMMARY: 6 errors from 6 contexts (suppressed: 0 from   0)
> aca_memory_leak_test

- include/aca_ovs_l2_programmer.h
- include/aca_ovs_l3_programmer.h
- include/aca_vlan_manager.h
- src/comm/aca_comm_mgr.cpp
- src/dp_abstraction/aca_dataplane_ovs.cpp
- src/ovs/aca_ovs_l2_programmer.cpp
- src/ovs/aca_ovs_l3_programmer.cpp
- src/ovs/aca_vlan_manager.cpp
- test/CMakeLists.txt
- test/func_tests/gs_tests.cpp
- test/gtest/aca_test_ovs_l2.cpp
- test/gtest/aca_test_ovs_l3.cpp
- test/gtest/aca_test_ovs_util.cpp
This PR added the ability to delete a port configuration on host. The change added:
1. support for port delete
1. support for L2 neighbor delete
1. support for L3 neighbor delete
1. test case for the above and confirm with traffic
1. test refactoring for reuse and clean up
1. new test cases of L3 neighbor
Also fixes:futurewei-cloud/alcor#103
> [Feature] Adding support for port delete, also include L2/L3 neighbor delete

- docs/logs/perf_X_neighbors_physical.log
- include/aca_config.h
- include/aca_ovs_l2_programmer.h
- include/aca_util.h
- include/aca_vlan_manager.h
- src/aca_main.cpp
- src/comm/aca_comm_mgr.cpp
- src/dhcp/aca_dhcp_state_handler.cpp
- src/dp_abstraction/aca_dataplane_ovs.cpp
- src/net_config/aca_net_config.cpp
- src/ovs/aca_ovs_l2_programmer.cpp
- src/ovs/aca_ovs_l3_programmer.cpp
- src/ovs/aca_vlan_manager.cpp
- src/zeta/aca_oam_server.cpp
- src/zeta/aca_zeta_programming.cpp
- test/func_tests/gs_tests.cpp
- test/gtest/aca_test_main.cpp
- test/gtest/aca_test_ovs_l2.cpp
- test/gtest/aca_test_ovs_util.cpp
This PR includes:
1. change _vpcs_table hashtable to use tunnel ID as the key to support Zeta
1. update the corresponding implementation for the above
1. added test case for upto 1,000,000 neighbors in one goal state for perf profiling in progress
1. added more metric data collection for ACA perf analysis
1. confirm all test cases are passing
> change _vpcs_table hashtable to use tunnel ID as key and added metric data points

- test/gtest/aca_test_zeta_programming.cpp
- test/zeta-aca-test_controllerScript/run.py
The goal of this PR is to add a scale test for port creation, e.g. 100,000 ports creation in both Zeta and ACA, respectively. 
Changes include:
- Enabled user to test with amount of ports to create, up to 1,000,000 ports.
- Enabled user to test with different test cases. If a number of port to create is given to the pseudo controller, it will create that many ports, then run the DISABLED_zeta_scale_CHILD and DISABLED_zeta_scale_PARENT test cases; otherwise it will create two ports, and run the DISABLED_zeta_gateway_path_CHILD and DISABLED_zeta_gateway_path_PARENT test cases.
> [Zeta Test] Added Scale test for Zeta/ACA integration

- test/gtest/aca_test_zeta_programming.cpp
- test/zeta-aca-test_controllerScript/run.py
The goal of this PR is to improve the scale test. 
Changes include: 
- Changed the formatting of port_id, which leads to errors in `DISABLED_zeta_scale_CHILD` and `DISABLED_zeta_scale_PARENT`, which were unseen before. For more info, please refer to [here](https://github.com/futurewei-cloud/alcor-control-agent/pull/180#issuecomment-747672395).
- Optimized error handling when calling the Zeta APIs, if there's an unsuccessful call, the pseudo controller will stop right there.
- Added concurrent execution for gtests, which can potentially save a lot of time when creating more and more ports.
- Added logic to ping between port after all ports are set successfully.
- Optimized `DISABLED_zeta_scale_CHILD` and `DISABLED_zeta_scale_PARENT`, added logic to clean up existing bridges before the …
> [Zeta] Improved scale test with corrected port_id, concurrent execution for GTests.

- include/aca_zeta_programming.h
- src/zeta/aca_zeta_programming.cpp
- test/gtest/aca_test_oam.cpp
- test/gtest/aca_test_zeta_programming.cpp
Add ZGC gateway entries' MAC addresses. #189 
@er1cthe0ne There seems to be no quit error on my computer, but there is a small probability that the aca_zeta_scale_test will not pass. The cause is being investigated.
> Zeta Data path integration fixes

- include/aca_zeta_oam_server.h
- src/zeta/aca_zeta_oam_server.cpp
- src/zeta/aca_zeta_programming.cpp
#188  Fix concurrency errors and change the cache data structure to CTSL::HashMap. @er1cthe0ne 
1. The lock is still retained (an error will occur after the lock is removed), but it is moved inside the method.
2. In my environment, there will be no concurrent quit errors.
> [Zeta] fix concurrency errors and change the oam_cache data structure (#188)

- src/zeta/aca_zeta_programming.cpp
- test/gtest/aca_test_zeta_programming.cpp
This PR is created to replace the existing `_create_oam_ofp ` with a new thread, which listens to the `oam_port` and calls the `oams_recv` with the packet info received. 
This PR achieves the following:
1. When user runs `DISABLED_zeta_scale_PARENT`/`DISABLED_zeta_scale_CHILD` with Zeta already setup, and a correct `./test/gtest/aca_data.json`, it starts a new thread that listens to the `oam_port` for 120 seconds, before it dies.
2. When the thread receives a packet, it prints out the packet and then calls the `oams_recv`.
Part of output when doing a `ping -I port_1 -c1 port_2`, when a ping packets traversed through the Zeta gateway successfully, the OAM packet will come down and will be captured below:
```
Packet length is 44
Got this udp packet when listening to port 8300
00000   00 00 …
```
> [Zeta] added non-ovs path for handling OAM packet

- src/zeta/aca_zeta_oam_server.cpp
The purpose of this PR is to add more details for the direct path. 
Proof of ping request went through the direct path:
Before rule is set up:
```
~$ sudo ovs-ofctl dump-flows br-tun
cookie=0x0, duration=3.174s, table=0, n_packets=29, n_bytes=3608, priority=1,in_port="patch-int" actions=resubmit(,2)
cookie=0x0, duration=3.133s, table=0, n_packets=0, n_bytes=0, priority=25,in_port="vxlan-generic" actions=resubmit(,4)
cookie=0x0, duration=3.186s, table=0, n_packets=0, n_bytes=0, priority=0 actions=NORMAL
cookie=0x0, duration=3.157s, table=2, n_packets=0, n_bytes=0, priority=25,arp,in_port="patch-int",arp_op=1 actions=resubmit(,51)
cookie=0x0, duration=3.149s, table=2, n_packets=0, n_bytes=0, priority=25,icmp,in_port="patch-int",icmp_type=8 actions=resubmit(,52)
cookie=0x0, duration=3.169s, …
```
> [Zeta] Added more details on for direct path programming logic.

- include/aca_zeta_oam_server.h
- include/aca_zeta_programming.h
- src/ovs/aca_ovs_control.cpp
- src/zeta/aca_zeta_oam_server.cpp
- src/zeta/aca_zeta_programming.cpp
#197 
1. Clean up oam cache and OVS code.
2. Fixed the error in uint ACA_Zeta_Programming::get_group_id(string zeta_gateway_id).
3. Passed all the tests in my environment.
```
[       OK ] zeta_programming_test_cases.DISABLED_zeta_scale_CHILD (120537 ms)
[----------] 1 test from zeta_programming_test_cases (120537 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (120537 ms total)
[  PASSED  ] 1 test.
```
```
[       OK ] zeta_programming_test_cases.create_auxgateway_test (329 ms)
[----------] 3 tests from zeta_programming_test_cases (369 ms total)
[----------] Global test environment tear-down
[==========] 41 tests from 8 test suites ran. (7104 ms total)
[  PASSED  ] 41 tests.
YOU HAVE 12 DISABLED TESTS
```
> [Zeta] clean up oam cache and OVS code

- include/aca_vlan_manager.h
- src/ovs/aca_vlan_manager.cpp
- test/gtest/aca_test_zeta_programming.cpp
- test/zeta-aca-test_controllerScript/README.md
- test/zeta-aca-test_controllerScript/run.py
This PR does the following:
1. Address the concurrency problem for the vpc_id inside aca.
2. Created new test case, `DISABLED_zeta_scale_container `, to replace the original `DISABLED_zeta_scale_PARENT` and `DISABLED_zeta_scale_CHILD`, as multiple internal ports are proved not working for our ping test.
3. Modified the logic for the pseudo controller according to the new test case, please refer to the updated `test/zeta-aca-test_controllerScript/README.md test/zeta-aca-test_controllerScript/README.md ` for more information.
Sample output for running the update pseudo controller:
[no_param.txt](https://github.com/futurewei-cloud/alcor-control-agent/files/5852497/no_param.txt)
[with_param.txt](https://github.com/futurewei-cloud/alcor-control-agent/files/5852498/with_param.txt)
> [Zeta] Updated Pseudo Controller with new test case to replace the internal port testcases; added back locks to address concurrency issue.

- .travis.yml
- build/Dockerfile
- include/aca_zeta_programming.h
- src/ovs/aca_arp_responder.cpp
- src/zeta/aca_zeta_programming.cpp
- test/gtest/aca_test_ovs_l2.cpp
- test/gtest/aca_test_zeta_programming.cpp
- test/travis_test/build_2_container.sh
This PR attemps to do the following:
1. Enable the CI to run the 2_ports_CREATE_test_traffic tests, with docker network created, fixed IPs assigned to the two containers, and the 2_ports_CREATE_test_traffic tests called with the above IPs.
> Fix for CI running the 2_ports_CREATE_test_traffic tests

- src/dp_abstraction/aca_dataplane_ovs.cpp
This PR proposes temporary fix for the following scenarios:
* Nova sends port update operation with nonempty device_id and device_owner (of value compute:nova). This request should be treated as CREATE from Alcor perspective.
* Nova sends port update operation with empty device_id and device_owner. This request should be treated as DELETE.
The ultimate fix should be in Port Manager as the resource owner. We proposes this fix as a short-term solution to verify E2E success.
> Temporary fix for port update/create

- include/aca_grpc.h
- src/comm/aca_grpc.cpp
- test/CMakeLists.txt
- test/func_tests/gs_tests.cpp
- test/gtest/aca_test_main.cpp
- test/gtest/aca_test_on_demand.cpp
- test/travis_test/build_2_container.sh
This PR does the following:
1. Added functionality and option for `gs_tests` to run as a grpc client/server.
2. Added `DISABLED_grpc_client_connectivity_test` disable testcase, which tests the basic grpc channel connectivity.
3. Improved grpc client channel's connectivity check by changing the condition to check.
How to run the new testcase:
1. On machine one, run `sudo ./build/tests/gs_tests -m -d` to start the grpc server, which pretends to be the NCM.
2. On machine two, run `sudo ./build/tests/aca_tests --gtest_also_run_disabled_tests --gtest_filter=*DISABLED_grpc_client_connectivity_test -a machine_one_ip -p 54321` to trigger the testcase.
> Grpc unit test

- src/dhcp/aca_dhcp_server.cpp
- src/ovs/aca_ovs_l3_programmer.cpp
The purpose of this PR is to update the subnet routing correctly.
We saw that, in the current code, if we're using an existing router subnet table entry and trying to update it, the entry stays the same after the "update" lines. So we decided to add some lines to ensure the updated entry is in the map.
> Update subnet routing correctly.

- src/aca_main.cpp
- src/ovs/aca_ovs_l2_programmer.cpp
This PR does the following:
1. Prints better log, when ACA has one of the needed bridges but doesn't have the other one (br-int and br-tun), so that user know what to do with invalid environment.
2. Refactored logic for ovs-bridge checking, so that it behaves correctly when `br-int` does NOT exist but `br-tun` exists. Closes #249 .
3. Replaces PR #230
> Refactor ovs-bridges checking logic and improve logging

- include/aca_on_demand_engine.h
- src/aca_main.cpp
- test/func_tests/gs_tests.cpp
- test/gtest/aca_test_main.cpp
What does this PR does:
This PR makes the sizes of thread pools change according to the number of cores of the host.
In the current implementation, the sizes of the thread pools are fixed to 16, which is decided based on the core number of the test machine (24). It will be more ideal if the sizes of the thread pools change based on the number of cores of the host machine.
From previous tests, we found that, for `x` number of cores, it is more efficient to set the size of both thread pools to be `x * (2/3)`, which means the total size of the thread pools is `x * (4/3)`. For example, for a host with 24 cores, we would set the sizes of both thread pools to be 16.
> Adjustable thread pool size based on host core number 

- build/aca-machine-init.sh
- build/build.sh
- src/aca_main.cpp
This PR does the following:
1. Upgraded Pulsar to version 2.8.0, which closes #262 
2. Enhanced `build/aca-machine-init.sh`, so that it can compile the code successfully.
Sample output:
```
Start of RunServer, pool size 16
Running a grpc client in a separate thread id: 140418830612224
Trying to init a new sub to connect to the NCM
lo       AF_PACKET (17)
enp2s0f0 AF_PACKET (17)
enp2s0f1 AF_PACKET (17)
enx00116b7394bd AF_PACKET (17)
docker0  AF_PACKET (17)
ovs-system AF_PACKET (17)
br-int   AF_PACKET (17)
br-tun   AF_PACKET (17)
vxlan_sys_4789 AF_PACKET (17)
31b980f306924_c AF_PACKET (17)
31b980f306924_l AF_PACKET (17)
lo       AF_INET (2)
address: <xxxx>
enp2s0f1 AF_INET (2)
address: <yyyy>
enx00116b7394bd AF_INET (2)
address: <zzzz>
docker0  AF_INET (2)
address: <aaaa>
Current Host IP: …
```
> Update pulsar to 2.8.0

- include/of_controller.h
- src/ovs/of_controller.cpp
That this PR does:
- Fixes potential deadlock when adding an OpenFlow connection. Fixes #269 .
- Put add/remove connection actions under the same lock/unlock sequence, making the process atomic.
> Fixing potential deadlock when adding an OpenFlow Connection

- include/aca_grpc.h
- src/comm/aca_grpc.cpp
What this PR does:
- Added functionality to ACA's gRPC server, which notifies the client(NCM) a requetst is finished, meaning that the onCompleted() in a Java gRPC client will be invoked.
Note:
- In this async gRPC model, please note that each time when a `tag`(the request) is retrieved from the `CompletionQueue`, one and only one action shall be performed(such as read/write/finish/delete request object), if you perform multiple actions in one `CompletionQueue->Next`, the program may crash.
> Added .Finish call for gRPC server

- src/ovs/ovs_control.cpp
1. Uncomment parse packet in ovs control vconn code path
2. Fix redefinition of header files in ovs control
3. Add description of ovs_control code path being legacy and deprecated
> Add description of deprecated code path of ovs control, but also enable parse packet in it

- src/ovs/aca_ovs_l3_programmer.cpp
What does this PR do:
This PR implemented the routing rule update with GoalStateV2.
NOTE:
Please don't merge it until it is tested.
> Routing rule gsv2
